from __future__ import annotations

import json
import uuid
from collections import defaultdict, deque
from typing import Any, Deque, Dict, Iterable, Mapping, Protocol

from src.tasklists.task import Task
from src.tasklists.task_list import TaskList
from src.tasklists.task_states import TASK_STATE_COMPLETED

from .node import WorkflowNode
from .result import VALID_OUTCOMES, WorkflowResult


class WorkflowExecutor(Protocol):
    def execute(self, node: WorkflowNode) -> WorkflowResult:
        ...


class FakeWorkflowExecutor:
    """Deterministic scripted executor for unit tests and workflow dry runs."""

    def __init__(self, results: Mapping[str, WorkflowResult | Iterable[WorkflowResult]]):
        self._results: Dict[str, Deque[WorkflowResult]] = {}
        for node_id, value in results.items():
            if isinstance(value, WorkflowResult):
                queue = deque([value])
            else:
                queue = deque(value)
            self._results[node_id] = queue
        self.calls: list[str] = []
        self.feedback_seen: Dict[str, list[str]] = defaultdict(list)

    def execute(self, node: WorkflowNode) -> WorkflowResult:
        self.calls.append(node.id)
        feedback = node.metadata.get("feedback")
        if feedback:
            self.feedback_seen[node.id].append(str(feedback))
        queue = self._results.get(node.id)
        if not queue:
            raise RuntimeError(f"No fake result configured for workflow node '{node.id}'")
        if len(queue) == 1:
            return queue[0]
        return queue.popleft()


def classify_semantic_outcome(text: str, execution_state: str) -> str:
    """Classify semantic outcome without equating normal execution with success.

    Structured JSON is preferred. Free text is only classified as blocked when
    it contains strong blocking language; otherwise a completed call remains
    inconclusive rather than being promoted to success.
    """

    if execution_state != "completed":
        return "failed"

    raw = (text or "").strip()
    if raw:
        try:
            payload = json.loads(raw)
            if isinstance(payload, dict):
                outcome = str(payload.get("outcome") or "").strip().lower()
                if outcome in VALID_OUTCOMES:
                    return outcome
        except (TypeError, ValueError, json.JSONDecodeError):
            pass

    lowered = raw.lower()
    blocked_markers = (
        "blocked",
        "cannot access",
        "can't access",
        "could not access",
        "unable to access",
        "cannot complete",
        "could not complete",
        "unable to complete",
    )
    if any(marker in lowered for marker in blocked_markers):
        return "blocked"

    return "inconclusive"


class TaskListWorkflowExecutor:
    """Adapter from WorkflowNode execution to Lucy's existing TaskList path.

    Nodes may point at an existing ``tasklist`` id. Otherwise the adapter
    persists a one-task TaskList for the node, executes it through
    AutomationProcessor.execute_tasklist(), then reads the persisted task
    execution record for semantic result and metrics.
    """

    def __init__(
        self,
        *,
        automation_processor: Any,
        storage: Any,
        account_name: str,
        primary_agent: Any,
        account: Dict[str, Any],
        conversation_id: str = "workflow",
        secondary_agent: Any = None,
        processor_factory: Any = None,
        correlation_id: str | None = None,
    ) -> None:
        self.automation_processor = automation_processor
        self.storage = storage
        self.account_name = account_name
        self.primary_agent = primary_agent
        self.account = account
        self.conversation_id = conversation_id
        self.secondary_agent = secondary_agent
        self.processor_factory = processor_factory
        self.correlation_id = correlation_id

    def execute(self, node: WorkflowNode) -> WorkflowResult:
        tasklist_id = node.tasklist_id
        created_task_id: str | None = None

        if not tasklist_id:
            tasklist_id = f"workflow-{node.id}-{uuid.uuid4().hex[:8]}"
            created_task_id = f"{node.id}-work"
            task = Task(
                id=created_task_id,
                name=node.name,
                instructions=self._instructions_with_feedback(node),
                agent=node.agent_name,
                context=node.context_name,
            )
            tasklist = TaskList(
                id=tasklist_id,
                name=f"Workflow: {node.name}",
                description=f"Generated by WorkflowRunner for node {node.id}",
                tasks=[task],
                meta={"workflow_node_id": node.id},
            )
            self.storage.save_tasklist(self.account_name, tasklist_id, tasklist)

        caller_agent_name = (getattr(self.primary_agent, "name", "") or "").lower().strip()
        try:
            self.automation_processor.execute_tasklist(
                tasklist_id=tasklist_id,
                mode="multi-step",
                account_name=self.account_name,
                agent_name=caller_agent_name,
                conversation_id=self.conversation_id,
                correlation_id=self.correlation_id,
                context_name=node.context_name or "",
                primary_agent=self.primary_agent,
                account=self.account,
                secondary_agent=self.secondary_agent,
                processor_factory=self.processor_factory,
                worker_agent=node.agent_name,
            )
        except Exception as exc:
            return WorkflowResult(
                execution_state="error",
                outcome="failed",
                error=str(exc),
            )

        tasklist = self.storage.get_tasklist(self.account_name, tasklist_id)
        if tasklist is None:
            return WorkflowResult(
                execution_state="error",
                outcome="failed",
                error=f"TaskList '{tasklist_id}' was not found after execution",
            )

        task = tasklist.get_task(created_task_id) if created_task_id else self._last_executed_task(tasklist.tasks)
        if task is None:
            return WorkflowResult(
                execution_state="error",
                outcome="failed",
                error=f"TaskList '{tasklist_id}' has no executed task result",
            )

        record = self.storage.get_task_result(self.account_name, tasklist_id, task.id) or {}
        execution_state = "completed" if task.state == TASK_STATE_COMPLETED else "error"
        text = self._result_text(record, task.result)
        metrics = dict(record.get("metrics") or task.run_metrics or {})
        outcome = classify_semantic_outcome(text, execution_state)

        return WorkflowResult(
            execution_state=execution_state,
            outcome=outcome,
            text=text,
            metrics=metrics,
            error=record.get("error") or task.error,
        )

    @staticmethod
    def _instructions_with_feedback(node: WorkflowNode) -> str:
        instructions = node.instructions.strip()
        feedback = str(node.metadata.get("feedback") or "").strip()
        if feedback:
            instructions = f"{instructions}\n\nReview feedback from the previous attempt:\n{feedback}".strip()
        return instructions

    @staticmethod
    def _last_executed_task(tasks: list[Task]) -> Task | None:
        executed = [task for task in tasks if task.state != "Pending"]
        return executed[-1] if executed else (tasks[-1] if tasks else None)

    @staticmethod
    def _result_text(record: Dict[str, Any], inline_result: Any) -> str:
        result = record.get("result") if isinstance(record, dict) else None
        if not isinstance(result, dict):
            result = inline_result if isinstance(inline_result, dict) else {}
        output = result.get("output") if isinstance(result, dict) else None
        if output is not None:
            return str(output)
        if result:
            return json.dumps(result, default=str)
        return ""
